src/com/lingshang/bean/Cart.java
package com.lingshang.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Date:2020/10/24
 * Author:Ling
 * Description:表示购物车的类
 */
public class Cart implements Serializable { //取消session钝化

    //购物车中所有的购物项，以购物项中图书的id为键，以购物项为值
    private Map<String,CartItem> map=new HashMap<>();

    //当前购物车所有图书的总数量
    private Integer totalCount;

    //购物车中的所有图书的总金额
    private Double totalAmount;

    public Map<String, CartItem> getMap() {
        return map;
    }

    public void setMap(Map<String, CartItem> map) {
        this.map = map;
    }

    public Integer getTotalCount() {

        totalCount=0;

        for (CartItem cartItem : getCartItemList()) {
            totalCount+=cartItem.getCount();
        }
        return totalCount;
    }

    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    public Double getTotalAmount() {
        BigDecimal bigDecimal1=new BigDecimal("0.0"); //处理精度问题，防止出现长精度
        for (CartItem cartItem : getCartItemList()) {
            BigDecimal bigDecimal2=new BigDecimal(cartItem.getAmount()+"");
            bigDecimal1=bigDecimal1.add(bigDecimal2);
        }
        return bigDecimal1.doubleValue();
    }

    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }

    //获取所有的购物项
    public List<CartItem> getCartItemList()
    {
        return new ArrayList<>(map.values()); //map集合的键转化为list
    }

    //加入购物车
    public void addCartItem(Book book)
    {
        //根据图书id获取map集合中图书所对应的购物项
        CartItem cartItem = map.get(book.getId() + "");
        //判断购物车中是否存在此购物项
        if (cartItem==null)
        {
            //没有此购物项，是新添加的购物项（需要将book对象转化为购物项）
            cartItem=new CartItem();
            cartItem.setBook(book);
            cartItem.setCount(1);
            //将购物项添加到购物车的map中
            map.put(book.getId()+"",cartItem);
        }
        else
        {
            //购物车中已有此购物项，将此购物项的数量+1
            cartItem.setCount(cartItem.getCount()+1);
        }
    }

    //删除购物项
    public void deleteCartItem(String bookId)
    {
        map.remove(bookId);
    }

    //清空购物车
    public void clearCart()
    {
        map.clear();
    }

    //更新购物项的数量
    public void updateCount(String bookId,String countStr)
    {
        try {
            Integer count = Integer.parseInt(countStr);
            if(count>0){
                map.get(bookId).setCount(count);
            }
            else if(count==0){
                map.remove(bookId);
            }
        } catch (NumberFormatException e) {        }
    }
    
}

src/com/lingshang/servlet/CartServlet.java
package com.lingshang.servlet;

import com.lingshang.bean.Book;
import com.lingshang.bean.Cart;
import com.lingshang.service.BookService;
import com.lingshang.service.impl.BooksServiceImpl;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;

/**
 * Date:2020/10/24
 * Author:Ling
 * Description:
 */
public class CartServlet extends BaseServlet {

    private BookService bookService = new BooksServiceImpl();

    //添加图书到购物车
    protected void addCartItem(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        //获取请求参数
        String bookId = request.getParameter("bookId");
        //获取购物车对象，必须从session中获取，以保证在一次会话中操作的购物车是同一个
        HttpSession session = request.getSession();
        Cart cart = (Cart) session.getAttribute("cart");
        //判断购物车是否为第一次添加图书信息
        if (cart == null) {
            //第一次添加图书信息，重新创建购物车对象
            cart = new Cart();
        }

        //根据bookId获取图书信息
        Book book = bookService.getBookByBookId(bookId);
        //将图书信息添加到购物车中
        cart.addCartItem(book);

        //将购物车对象放在session中共享
        session.setAttribute("cart", cart);
        //将刚刚添加到购物车中的图书标题共享在session中，方便在页面中显示
        session.setAttribute("bookTitle", book.getTitle());
        //重定向到此操作的来源页面
        response.sendRedirect(request.getHeader("referer"));
    }

    //删除购物项
    protected void deleteCartItem(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
    {
        //获取请求参数
        String bookId = request.getParameter("bookId");
        //获取session对象
        HttpSession session = request.getSession();
        //从session中获取购物车对象
        Cart cart = (Cart) session.getAttribute("cart");
        //根据bookId从购物车中删除购物项
        cart.deleteCartItem(bookId);
        //重定向到此操作的来源页面
        response.sendRedirect(request.getHeader("referer"));
    }

    //清空购物车
    protected void clearCart(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
    {
        //获取session对象
        HttpSession session = request.getSession();
        //从session中获取购物车对象
        Cart cart = (Cart) session.getAttribute("cart");
        //清空购物车
        cart.clearCart();
        //重定向到此操作的来源页面
        response.sendRedirect(request.getHeader("referer"));
    }

    //更新购物项的数量
    protected void updateCount(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
    {
        //获取请求参数
        String bookId = request.getParameter("bookId");
        String countStr = request.getParameter("count");

        //获取session对象
        HttpSession session = request.getSession();
        //从session中获取购物车对象
        Cart cart = (Cart) session.getAttribute("cart");

        //更新购物项的数量
        cart.updateCount(bookId,countStr);
        //重定向到此操作的来源页面
        response.sendRedirect(request.getHeader("referer"));
    }
}

web/pages/cart/cart.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
<meta charset="UTF-8">
<title>购物车</title>
<jsp:include page="/WEB-INF/include/base.jsp"></jsp:include>
<script type="text/javascript">
	$(function ()
	{
		$(".countInput").change(function ()
		{
			var count=$(this).val();
			var bookId=$(this).attr("bookId");
			location="CartServlet?method=updateCount&bookId="+bookId+"&count="+count;
		});
		//图书数量加
		$(".plusCount").click(function ()
		{
			var count=Number($(this).next().val())+1;
			var bookId=$(this).next().attr("bookId");
			location="CartServlet?method=updateCount&bookId="+bookId+"&count="+count;
		});
		//图书数量减
		$(".minusCount").click(function ()
		{
			var count=Number($(this).prev().val())-1;
			var bookId=$(this).prev().attr("bookId");
			location="CartServlet?method=updateCount&bookId="+bookId+"&count="+count;
		});
	});
</script>
</head>
<body>
	
	<div id="header">
		<jsp:include page="/WEB-INF/include/logo.jsp"></jsp:include>
			<span class="wel_word">购物车</span>
		<jsp:include page="/WEB-INF/include/client_head.jsp"></jsp:include>
	</div>
	
	<div id="main">
	
		<c:if test="${not empty sessionScope.cart.map}">
			<table>
				<tr>
					<td>商品名称</td>
					<td>数量</td>
					<td>单价</td>
					<td>金额</td>
					<td>操作</td>
				</tr>

				<c:forEach items="${sessionScope.cart.cartItemList}" var="cartItem">
					<tr>
						<td>${pageScope.cartItem.book.title}</td>
						<td>
							<input type="button" value="+" class="plusCount">
							<input type="text" value="${pageScope.cartItem.count}" class="countInput" bookId="${pageScope.cartItem.book.id}" style="width: 40px;text-align: center">
							<input type="button" value="-" class="minusCount">
						</td>
						<td>${pageScope.cartItem.book.price}</td>
						<td>${pageScope.cartItem.amount}</td>
						<td><a href="CartServlet?method=deleteCartItem&bookId=${pageScope.cartItem.book.id}">删除</a></td>
					</tr>
				</c:forEach>

			</table>

			<div class="cart_info">
				<span class="cart_span">购物车中共有<span class="b_count">${sessionScope.cart.totalCount}</span>件商品</span>
				<span class="cart_span">总金额<span class="b_price">${sessionScope.cart.totalAmount}</span>元</span>
				<span class="cart_span"><a href="">继续购物</a></span>
				<span class="cart_span"><a href="CartServlet?method=clearCart">清空购物车</a></span>
				<span class="cart_span"><a href="OrderClientServlet?method=checkout">去结账</a></span>
			</div>

		</c:if>
		
		<c:if test="${empty sessionScope.cart.map}">
			<br><br><br><br><br><br><br><br><br><br>
			<center>
				<h2>亲，购物车空空如也。。。</h2><a href="">去购物</a>
			</center>
		</c:if>

	</div>
	
	<div id="bottom">
		<span>
			宸星书城.Copyright &copy;2020
		</span>
	</div>
</body>
</html>

web/pages/cart/checkout.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
<meta charset="UTF-8">
<title>结算页面</title>
<jsp:include page="/WEB-INF/include/base.jsp"></jsp:include>
<style type="text/css">
	h1 {
		text-align: center;
		margin-top: 200px;
	}
</style>
</head>
<body>
	
	<div id="header">
		<jsp:include page="/WEB-INF/include/logo.jsp"></jsp:include>
		<span class="wel_word">结算</span>
		<jsp:include page="/WEB-INF/include/client_head.jsp"></jsp:include>
	</div>
	
	<div id="main">
		
		<h1>你的订单已结算，订单号为${sessionScope.orderId}</h1>
		
	
	</div>
	
	<div id="bottom">
		<span>
			宸星书城.Copyright &copy;2020
		</span>
	</div>
</body>
</html>